// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using HotChocolate;
using HotChocolate.Types.Relay;
using Microsoft.EntityFrameworkCore;

namespace GraphQL_ClassLibrary.Models;

public partial class Author
{
    [ID]
    [Key]
    [GraphQLDescription("Shown as an ID scaler type. But is of type GUID (example: \"cef5cbe5e277481e8870ffb1e8d0c0f7\")")]
    public Guid Id { get; set; }

    [StringLength(100)]
    public string Name { get; set; }

    [InverseProperty("Author")]
    public virtual ICollection<Book> Books { get; set; } = new List<Book>();
}