// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace GraphQL_ClassLibrary.Models;

public partial class Book
{
    [Key]
    public Guid Id { get; set; }

    [StringLength(250)]
    public string Title { get; set; }

    public int? ReleaseYear { get; set; }

    public Guid AuthorId { get; set; }

    [ForeignKey("AuthorId")]
    [InverseProperty("Books")]
    public virtual Author Author { get; set; }
}