// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Webhook_System.Models;

public partial class Webhook
{
    [Key]
    public Guid Id { get; set; }

    [StringLength(300)]
    public string Url { get; set; } = string.Empty;

    [StringLength(100)]
    public string EventType { get; set; } = string.Empty;
}