// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Webhook_System.Models;

public partial class Webhook
{
    public Guid Id { get; set; }

    public string Url { get; set; }

    public string EventType { get; set; }
}