services:
  db_source:
    image: postgres:14
    container_name: db_source
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: sourcedb
    volumes:
      - ./init_source_db.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5433:5432"

  db_target:
    image: postgres:14
    container_name: db_target
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: targetdb
    ports:
      - "5434:5432"
