services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: sql_express
    environment:
      SA_PASSWORD: "admin123!"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - ./init:/init
    networks:
      - db-network

  db_init:
    image: mcr.microsoft.com/mssql-tools
    depends_on:
      - sqlserver
    volumes:
      - ./init:/init
    entrypoint: >
      bash -c "
        /opt/mssql-tools/bin/sqlcmd -S sqlserver -U SA -P 'admin123!' -i /init/init.sql
      "
    networks:
      - db-network

networks:
  db-network:
    driver: bridge
